// Generated by CIRCT firtool-1.62.0
module Bus(
  input         clock,
                reset,
  input  [15:0] io_value1,
                io_value2,
  input         io_loadingValues,
  output [15:0] io_outputGCD,
  output        io_outputValid,
  output [31:0] main_memory_adr_o,
                led_matrix_0_adr_o,
                switches_0_adr_o
);

  reg [15:0] x;
  reg [15:0] y;
  always @(posedge clock) begin
    if (io_loadingValues) begin
      x <= io_value1;
      y <= io_value2;
    end
    else if (x > y)
      x <= x - y;
    else
      y <= y - x;
  end // always @(posedge)
  assign io_outputGCD = x;
  assign io_outputValid = y == 16'h0;
  assign main_memory_adr_o = 32'h4;
  assign led_matrix_0_adr_o = 32'h4;
  assign switches_0_adr_o = 32'h4;
endmodule

