// Generated by CIRCT firtool-1.62.0
module SharedBus(
  input         clock,
                reset,
  input  [31:0] cpu_data_interface_adr_o,
                cpu_data_interface_dat_o,
  input  [3:0]  cpu_data_interface_sel_o,
  input         cpu_data_interface_we_o,
                cpu_data_interface_stb_o,
                cpu_data_interface_cyc_o,
  output [31:0] cpu_data_interface_dat_i,
  output        cpu_data_interface_ack_i,
                cpu_data_interface_err_i,
  input  [31:0] cpu_instruction_interface_adr_o,
                cpu_instruction_interface_dat_o,
  input  [3:0]  cpu_instruction_interface_sel_o,
  input         cpu_instruction_interface_we_o,
                cpu_instruction_interface_stb_o,
                cpu_instruction_interface_cyc_o,
  output [31:0] cpu_instruction_interface_dat_i,
  output        cpu_instruction_interface_ack_i,
                cpu_instruction_interface_err_i,
  input  [31:0] dummy_master_mux_test_adr_o,
                dummy_master_mux_test_dat_o,
  input  [3:0]  dummy_master_mux_test_sel_o,
  input         dummy_master_mux_test_we_o,
                dummy_master_mux_test_stb_o,
                dummy_master_mux_test_cyc_o,
  output [31:0] dummy_master_mux_test_dat_i,
  output        dummy_master_mux_test_ack_i,
                dummy_master_mux_test_err_i,
  input  [31:0] dummy_master_mux_test2_adr_o,
                dummy_master_mux_test2_dat_o,
  input  [3:0]  dummy_master_mux_test2_sel_o,
  input         dummy_master_mux_test2_we_o,
                dummy_master_mux_test2_stb_o,
                dummy_master_mux_test2_cyc_o,
  output [31:0] dummy_master_mux_test2_dat_i,
  output        dummy_master_mux_test2_ack_i,
                dummy_master_mux_test2_err_i,
  output [31:0] main_memory_adr_i,
                main_memory_dat_i,
  output [3:0]  main_memory_sel_i,
  output        main_memory_we_i,
                main_memory_stb_i,
                main_memory_cyc_i,
  input  [31:0] main_memory_dat_o,
  input         main_memory_ack_o,
                main_memory_err_o,
  output [31:0] led_matrix_0_adr_i,
                led_matrix_0_dat_i,
  output [3:0]  led_matrix_0_sel_i,
  output        led_matrix_0_we_i,
                led_matrix_0_stb_i,
                led_matrix_0_cyc_i,
  input  [31:0] led_matrix_0_dat_o,
  input         led_matrix_0_ack_o,
                led_matrix_0_err_o,
  output [31:0] switches_0_adr_i,
                switches_0_dat_i,
  output [3:0]  switches_0_sel_i,
  output        switches_0_we_i,
                switches_0_stb_i,
                switches_0_cyc_i,
  input  [31:0] switches_0_dat_o,
  input         switches_0_ack_o,
                switches_0_err_o
);

  reg              cpu_data_interface_mask;
  reg              cpu_instruction_interface_mask;
  reg              dummy_master_mux_test_mask;
  wire             cpu_instruction_interface_unmasked_grant =
    ~cpu_data_interface_cyc_o & cpu_instruction_interface_cyc_o;
  wire             dummy_master_mux_test_unmasked_grant =
    ~cpu_data_interface_cyc_o & ~cpu_instruction_interface_cyc_o
    & dummy_master_mux_test_cyc_o;
  wire             dummy_master_mux_test2_unmasked_grant =
    ~cpu_data_interface_cyc_o & ~cpu_instruction_interface_cyc_o
    & ~dummy_master_mux_test_cyc_o & dummy_master_mux_test2_cyc_o;
  wire             maskedGrantVec_0 = cpu_data_interface_cyc_o & cpu_data_interface_mask;
  wire             cpu_instruction_interface_masked_input =
    cpu_instruction_interface_cyc_o & cpu_instruction_interface_mask;
  wire             dummy_master_mux_test_masked_input =
    dummy_master_mux_test_cyc_o & dummy_master_mux_test_mask;
  wire             maskedGrantVec_1 =
    ~maskedGrantVec_0 & cpu_instruction_interface_masked_input;
  wire             maskedGrantVec_2 =
    ~maskedGrantVec_0 & ~cpu_instruction_interface_masked_input
    & dummy_master_mux_test_masked_input;
  wire             maskedGrantVec_3 =
    ~maskedGrantVec_0 & ~cpu_instruction_interface_masked_input
    & ~dummy_master_mux_test_masked_input & dummy_master_mux_test2_cyc_o;
  wire [3:0]       unmaskedGrantVec =
    {dummy_master_mux_test2_unmasked_grant,
     dummy_master_mux_test_unmasked_grant,
     cpu_instruction_interface_unmasked_grant,
     cpu_data_interface_cyc_o};
  reg              cpu_data_interface_grant;
  reg              cpu_instruction_interface_grant;
  reg              dummy_master_mux_test_grant;
  reg              dummy_master_mux_test2_grant;
  reg              cyc_out;
  wire [3:0]       _GEN =
    {maskedGrantVec_3, maskedGrantVec_2, maskedGrantVec_1, maskedGrantVec_0};
  wire [1:0]       masterSelect =
    (|_GEN)
      ? {|{maskedGrantVec_3, maskedGrantVec_2}, maskedGrantVec_3 | maskedGrantVec_1}
      : (|unmaskedGrantVec)
          ? {|{dummy_master_mux_test2_unmasked_grant,
               dummy_master_mux_test_unmasked_grant},
             dummy_master_mux_test2_unmasked_grant
               | cpu_instruction_interface_unmasked_grant}
          : (|_GEN)
              ? {|{maskedGrantVec_3, maskedGrantVec_2},
                 maskedGrantVec_3 | maskedGrantVec_1}
              : (|unmaskedGrantVec)
                  ? {|{dummy_master_mux_test2_unmasked_grant,
                       dummy_master_mux_test_unmasked_grant},
                     dummy_master_mux_test2_unmasked_grant
                       | cpu_instruction_interface_unmasked_grant}
                  : (|_GEN)
                      ? {|{maskedGrantVec_3, maskedGrantVec_2},
                         maskedGrantVec_3 | maskedGrantVec_1}
                      : (|unmaskedGrantVec)
                          ? {|{dummy_master_mux_test2_unmasked_grant,
                               dummy_master_mux_test_unmasked_grant},
                             dummy_master_mux_test2_unmasked_grant
                               | cpu_instruction_interface_unmasked_grant}
                          : (|_GEN)
                              ? {|{maskedGrantVec_3, maskedGrantVec_2},
                                 maskedGrantVec_3 | maskedGrantVec_1}
                              : (|unmaskedGrantVec)
                                  ? {|{dummy_master_mux_test2_unmasked_grant,
                                       dummy_master_mux_test_unmasked_grant},
                                     dummy_master_mux_test2_unmasked_grant
                                       | cpu_instruction_interface_unmasked_grant}
                                  : 2'h0;
  wire [3:0][31:0] _GEN_0 =
    {{dummy_master_mux_test2_adr_o},
     {dummy_master_mux_test_adr_o},
     {cpu_instruction_interface_adr_o},
     {cpu_data_interface_adr_o}};
  wire [3:0][31:0] _GEN_1 =
    {{dummy_master_mux_test2_dat_o},
     {dummy_master_mux_test_dat_o},
     {cpu_instruction_interface_dat_o},
     {cpu_data_interface_dat_o}};
  wire [3:0][3:0]  _GEN_2 =
    {{dummy_master_mux_test2_sel_o},
     {dummy_master_mux_test_sel_o},
     {cpu_instruction_interface_sel_o},
     {cpu_data_interface_sel_o}};
  wire [3:0]       _GEN_3 =
    {{dummy_master_mux_test2_we_o},
     {dummy_master_mux_test_we_o},
     {cpu_instruction_interface_we_o},
     {cpu_data_interface_we_o}};
  wire [3:0]       _GEN_4 =
    {{dummy_master_mux_test2_stb_o},
     {dummy_master_mux_test_stb_o},
     {cpu_instruction_interface_stb_o},
     {cpu_data_interface_stb_o}};
  wire [3:0]       _GEN_5 =
    {{dummy_master_mux_test2_cyc_o},
     {dummy_master_mux_test_cyc_o},
     {cpu_instruction_interface_cyc_o},
     {cpu_data_interface_cyc_o}};
  wire             _dat_r_cond_T_2 = _GEN_0[masterSelect] > 32'hEFFFFFFF;
  wire             _dat_r_cond_T_4 = _GEN_0[masterSelect] > 32'hF0000DAB;
  wire [31:0]      dat_r =
    _GEN_0[masterSelect][31:28] != 4'hF
      ? main_memory_dat_o
      : _dat_r_cond_T_2 & _GEN_0[masterSelect] < 32'hF0000DAC
          ? led_matrix_0_dat_o
          : _dat_r_cond_T_4 & _GEN_0[masterSelect] < 32'hF0000DB0
              ? switches_0_dat_o
              : main_memory_dat_o;
  wire             ack = main_memory_ack_o | led_matrix_0_ack_o | switches_0_ack_o;
  wire             err = main_memory_err_o | led_matrix_0_err_o | switches_0_err_o;
  wire             _switches_0_stb_i_T = _GEN_4[masterSelect] & _GEN_5[masterSelect];
  always @(posedge clock) begin
    cpu_data_interface_mask <= masterSelect == 2'h0;
    cpu_instruction_interface_mask <= ~(masterSelect[1]);
    dummy_master_mux_test_mask <= masterSelect != 2'h3;
    if (|_GEN) begin
      cpu_data_interface_grant <= maskedGrantVec_0;
      cpu_instruction_interface_grant <= maskedGrantVec_1;
      dummy_master_mux_test_grant <= maskedGrantVec_2;
      dummy_master_mux_test2_grant <= maskedGrantVec_3;
    end
    else if (|unmaskedGrantVec) begin
      cpu_data_interface_grant <= cpu_data_interface_cyc_o;
      cpu_instruction_interface_grant <= cpu_instruction_interface_unmasked_grant;
      dummy_master_mux_test_grant <= dummy_master_mux_test_unmasked_grant;
      dummy_master_mux_test2_grant <= dummy_master_mux_test2_unmasked_grant;
    end
    cyc_out <=
      |{dummy_master_mux_test2_cyc_o,
        dummy_master_mux_test_cyc_o,
        cpu_instruction_interface_cyc_o,
        cpu_data_interface_cyc_o};
  end // always @(posedge)
  assign cpu_data_interface_dat_i = dat_r;
  assign cpu_data_interface_ack_i = ack & cpu_data_interface_grant;
  assign cpu_data_interface_err_i = err & cpu_data_interface_grant;
  assign cpu_instruction_interface_dat_i = dat_r;
  assign cpu_instruction_interface_ack_i = ack & cpu_instruction_interface_grant;
  assign cpu_instruction_interface_err_i = err & cpu_instruction_interface_grant;
  assign dummy_master_mux_test_dat_i = dat_r;
  assign dummy_master_mux_test_ack_i = ack & dummy_master_mux_test_grant;
  assign dummy_master_mux_test_err_i = err & dummy_master_mux_test_grant;
  assign dummy_master_mux_test2_dat_i = dat_r;
  assign dummy_master_mux_test2_ack_i = ack & dummy_master_mux_test2_grant;
  assign dummy_master_mux_test2_err_i = err & dummy_master_mux_test2_grant;
  assign main_memory_adr_i = _GEN_0[masterSelect];
  assign main_memory_dat_i = _GEN_1[masterSelect];
  assign main_memory_sel_i = _GEN_2[masterSelect];
  assign main_memory_we_i = _GEN_3[masterSelect];
  assign main_memory_stb_i = _switches_0_stb_i_T & _GEN_0[masterSelect][31:28] != 4'hF;
  assign main_memory_cyc_i = cyc_out;
  assign led_matrix_0_adr_i = _GEN_0[masterSelect];
  assign led_matrix_0_dat_i = _GEN_1[masterSelect];
  assign led_matrix_0_sel_i = _GEN_2[masterSelect];
  assign led_matrix_0_we_i = _GEN_3[masterSelect];
  assign led_matrix_0_stb_i =
    _switches_0_stb_i_T & _dat_r_cond_T_2 & _GEN_0[masterSelect] < 32'hF0000DAC;
  assign led_matrix_0_cyc_i = cyc_out;
  assign switches_0_adr_i = _GEN_0[masterSelect];
  assign switches_0_dat_i = _GEN_1[masterSelect];
  assign switches_0_sel_i = _GEN_2[masterSelect];
  assign switches_0_we_i = _GEN_3[masterSelect];
  assign switches_0_stb_i =
    _switches_0_stb_i_T & _dat_r_cond_T_4 & _GEN_0[masterSelect] < 32'hF0000DB0;
  assign switches_0_cyc_i = cyc_out;
endmodule

